### ISSUE TITLE
loopback.cfg wrong, cannot boot from ISO using loop-mount

### ISSUE THREAD

**Issue by UriHerrera** [nomad-desktop/nxos-iso#1]
Moved from: https://github.com/nomad-desktop/nxos-base-files/issues/3

> This does __not__ work:
> ```
> menuentry "nitrux_release_1.0.6.iso - casper 1.387
> " --class ubuntu {
>         iso_path="/boot/iso/nitrux_release_1.0.6.iso"
>         search --no-floppy --file ${iso_path} --set
>         live_args="for-casper --> iso-scan/filename=${iso_path} console-setup/layoutcode=de > locale=en_US timezone=Europe/Berlin username=me hostname=host noprompt max_loop=256"
>         custom_args=""
>        iso_args=" "
>        loopback loop ${iso_path}
 >       linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$iso_path quiet splash elevator=noop ${live_args} ${custom_args} ${iso_args}
>        initrd (loop)/casper/initrd.gz
>}
>```
>
> It cannot find `initrd.gz`. This is because the file is actually named differently:
>
> ```
> root@host:/mnt# find casper/
> (...)
> casper/initrd.lz
> ```
> 
> But `boot/grub/loopback.cfg` is __wrong__:
> 
> ```
> menuentry "Boot casper system" {
>   set gfxpayload=keep
>   linux /casper/vmlinuz boot=casper iso-scan/filename=$iso_path quiet splash elevator=noop
>   initrd /casper/initrd.gz
> }
>
> menuentry "Boot casper in safe graphics mode" {
>   set gfxpayload=keep
>   linux /casper/vmlinuz boot=casper iso-scan/filename=$iso_path xforcevesa nomodeset quiet splash > elevator=noop
>   initrd /casper/initrd.gz
> }
>
> menuentry "Boot casper in debug mode" {
>   set gfxpayload=keep
>   linux /casper/vmlinuz boot=casper iso-scan/filename=$iso_path elevator=noop
>  initrd /casper/initrd.gz
> }
> ```

**Comment by UriHerrera** [comment]
I've changed the affected file in the latest ISO, can you try it? @probonopd

**Comment by probonopd** [comment]
Thank you very much. Seems to be working with SystemImageKit now.

**Comment by star-buck** [comment]
What's systemimagekit?

**Comment by probonopd** [comment]
It's what I use to boot many different Live ISOs on the same machine: 
https://github.com/probonopd/SystemImageKit

**Comment by star-buck** [comment]
Ah, that one :)

**Comment by UriHerrera** [comment]
> Thank you very much. Seems to be working with SystemImageKit now.

Cool.

**Comment by luis-lavaire** [comment]
What does SystemImageKit needs to recognize an image?
