### ISSUE TITLE
No UEFI support on Live USB

### ISSUE THREAD

**Issue by AravindIM** [nomad-desktop/nxos-iso#5]
The Live USB installer only boots in legacy-bios mode.
No UEFI Partition found on Live USB Flashed with dd, Unetbootin and Etcher.
Only Legacy Boot Supported
Had To Install UEFI Bootloader seperately using Live USB of KDE Neon.

Hardware Specs of my PC:
Gigabyte GA-H81M-S
4 GB Ram
UEFI PC
Intel i3

**Comment by pablitok** [comment]
As a workaround, I extracted the iso files with 7zip like this
`7z x nitrux-iso-file.iso -o/media/usb`

**Comment by UriHerrera** [comment]
Nitrux OS version 1.0.10 boots in EFI and Legacy modes.
